# Generated by Django 3.2.10 on 2021-12-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Edepartment',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Erole',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='page',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employeeid',
            field=models.IntegerField(),
        ),
    ]
