# Generated by Django 3.2.10 on 2022-01-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20211230_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to='projectapp.person'),
        ),
    ]
